import { existsSync, mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import {
  DESKTOP_GIT_BASH_PRESET_ID,
  generateGitBashPreset,
  gitBashPresetComposition,
} from '../src/git-bash-preset.ts'
import { shippedPresetRoot } from '../src/profile.ts'

const BASH = 'C:\\Program Files\\Git\\bin\\bash.exe'

function temporaryHome(): string {
  const home = mkdtempSync(join(tmpdir(), 'dsh-git-bash-preset-'))
  mkdirSync(join(home, 'profiles'), { recursive: true })
  return home
}

/** Generate from the real shipped root into one temporary home. */
function generate(home: string, source: string, bashPath: string) {
  return generateGitBashPreset(shippedPresetRoot(), join(home, '.agent-presets'), source, bashPath)
}

const SOURCE = [
  '# keep this comment',
  '- id: tool-fs',
  "  name: '@deepseek-ai/dsh-tool-fs'",
  '',
  '# shell rows',
  '- id: tool-bash',
  "  name: '@deepseek-ai/dsh-tool-bash'",
  "  disabled: !!js process.platform === 'win32'",
  '',
  '- id: tool-pwsh',
  "  name: '@deepseek-ai/dsh-tool-pwsh'",
  "  disabled: !!js process.platform !== 'win32'",
  '',
  '- id: tool-todo',
  "  name: '@deepseek-ai/dsh-tool-todo'",
  '',
].join('\n')

describe('Git Bash preset composition', () => {
  it('replaces the one-shot shell rows and appends the persistent Git Bash pair', () => {
    const composed = gitBashPresetComposition(SOURCE, BASH)

    expect(composed).toContain('# keep this comment')
    expect(composed).toContain('id: tool-fs')
    expect(composed).toContain('id: tool-todo')
    expect(composed).not.toMatch(/id: tool-pwsh/u)
    expect(composed).not.toMatch(/id: tool-bash$/mu)
    expect(composed).toContain('id: shell-git-bash')
    expect(composed).toContain('@deepseek-ai/dsh-terminal-bash')
    expect(composed).toContain('shellDialect: bash')
    expect(composed).toContain(`shellPath: ${BASH}`)
    expect(composed).toContain('id: tool-bash-persistent')
    expect(composed).toContain('@deepseek-ai/dsh-tool-bash-persistent')
  })

  it('rejects a composition that is not a row sequence', () => {
    expect(() => gitBashPresetComposition('name: preset\n', BASH))
      .toThrow('must be a YAML sequence of rows')
  })
})

describe('Git Bash preset generation', () => {
  it('derives a preset from a shipped one and regenerates it without duplicating rows', () => {
    const home = temporaryHome()
    const generated = generate(home, 'standard', BASH)

    expect(generated.id).toBe(DESKTOP_GIT_BASH_PRESET_ID)
    expect(generated.directory).toBe(join(home, '.agent-presets', DESKTOP_GIT_BASH_PRESET_ID))
    expect(existsSync(join(generated.directory, '.dsh-desktop-generated'))).toBe(true)
    expect(readFileSync(join(generated.directory, 'preset.yml'), 'utf8')).toContain('name: Git Bash')
    expect(existsSync(join(generated.directory, 'agent.cordis.yml'))).toBe(true)

    const composition = readFileSync(join(generated.directory, 'agent.cordis.yml'), 'utf8')
    expect(composition).toContain(`shellPath: ${BASH}`)
    expect(composition).not.toContain('@deepseek-ai/dsh-tool-pwsh')
    expect(composition).toContain('@deepseek-ai/dsh-tool-todo')

    generate(home, 'standard', BASH)

    const regenerated = readFileSync(join(generated.directory, 'agent.cordis.yml'), 'utf8')
    expect(regenerated.match(/id: shell-git-bash/gu)).toHaveLength(1)
    expect(regenerated.match(/id: tool-bash-persistent/gu)).toHaveLength(1)
  })

  it('refuses to replace a preset the Desktop did not generate', () => {
    const home = temporaryHome()
    const foreign = join(home, '.agent-presets', DESKTOP_GIT_BASH_PRESET_ID)
    mkdirSync(foreign, { recursive: true })
    writeFileSync(join(foreign, 'agent.cordis.yml'), '- id: mine\n  name: mine\n')

    expect(() => generate(home, 'standard', BASH))
      .toThrow('was not generated by DSH Desktop')
    expect(readFileSync(join(foreign, 'agent.cordis.yml'), 'utf8')).toContain('id: mine')
  })

  it('fails loud on an unknown source preset', () => {
    expect(() => generate(temporaryHome(), 'no-such-preset', BASH))
      .toThrow('has no composition')
  })
})
