/** Generate the Desktop-owned Git Bash agent preset from a shipped preset. */

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { isMap, isSeq, parseDocument } from 'yaml'

/** Preset id the Desktop owns and regenerates. */
export const DESKTOP_GIT_BASH_PRESET_ID = 'git-bash'

/** Backend that runs one persistent bash shell through an explicit executable. */
const TERMINAL_PACKAGE = '@deepseek-ai/dsh-terminal-bash'

/** Model-facing tool over that backend. */
const PERSISTENT_TOOL_PACKAGE = '@deepseek-ai/dsh-tool-bash-persistent'

/**
 * Marker file recording that one preset directory is Desktop-generated.
 *
 * The generator refuses to touch a directory without it, so a user-authored
 * preset that happens to reuse the id is never silently replaced.
 */
const PRESET_MARKER_FILE = '.dsh-desktop-generated'

/**
 * Row ids the generator drops before appending its own shell rows.
 *
 * `tool-pwsh` and `tool-bash` are the one-shot tools over the host `ctx.shell`,
 * which stays the confined PowerShell on Windows; the other two are this
 * generator's own rows, dropped so a regeneration is idempotent.
 */
const REPLACED_ROW_IDS = new Set(['tool-pwsh', 'tool-bash', 'shell-git-bash', 'tool-bash-persistent'])

/** One generated preset's identity on disk. */
export interface GeneratedGitBashPreset {
  /** Preset id a session selects. */
  readonly id: string
  /** Absolute preset directory. */
  readonly directory: string
  /** Shipped preset id this generation derived from. */
  readonly source: string
}

/**
 * Build the Git Bash composition from one shipped preset's text.
 *
 * Comments and unrelated rows survive because the transform edits the parsed
 * document instead of re-emitting a hand-built row list.
 * @param source - the shipped preset composition text.
 * @param bashPath - absolute Git Bash executable the preset runs commands with.
 * @returns the composition text of the generated preset.
 */
export function gitBashPresetComposition(source: string, bashPath: string): string {
  const document = parseDocument(source, { prettyErrors: true })
  if (document.errors.length > 0) {
    throw new Error(`dsh-plugin-desktop: source preset is not valid YAML: ${document.errors.map(error => error.message).join('; ')}`)
  }
  const rows = document.contents
  if (!isSeq(rows)) throw new Error('dsh-plugin-desktop: source preset must be a YAML sequence of rows')
  for (let index = rows.items.length - 1; index >= 0; index -= 1) {
    const row = rows.items[index]
    if (isMap(row) && REPLACED_ROW_IDS.has(String(row.get('id')))) document.delete(index)
  }
  document.add({
    id: 'shell-git-bash',
    name: TERMINAL_PACKAGE,
    config: { shellDialect: 'bash', shellPath: bashPath },
  })
  document.add({
    id: 'tool-bash-persistent',
    name: PERSISTENT_TOOL_PACKAGE,
  })
  return document.toString()
}

/**
 * Materialize the Desktop Git Bash preset under a user preset root.
 *
 * Roots arrive as arguments so this module owns no preset-root policy: the
 * caller supplies the shipped root it derives from and the user root it writes
 * to. Regenerating replaces only a directory this generator owns, and a session
 * reaches the preset through the existing picker — the generator never writes
 * settings.
 * @param sourceRoot - root directory holding the shipped presets.
 * @param userRoot - user preset root the generated directory is written under.
 * @param source - shipped preset id to derive from.
 * @param bashPath - absolute Git Bash executable the preset runs commands with.
 * @returns the generated preset's identity on disk.
 */
export function generateGitBashPreset(
  sourceRoot: string,
  userRoot: string,
  source: string,
  bashPath: string,
): GeneratedGitBashPreset {
  const sourceDirectory = join(sourceRoot, source)
  const composition = join(sourceDirectory, 'agent.cordis.yml')
  if (!existsSync(composition)) {
    throw new Error(`dsh-plugin-desktop: shipped preset "${source}" has no composition`)
  }
  const directory = join(userRoot, DESKTOP_GIT_BASH_PRESET_ID)
  if (existsSync(directory) && !existsSync(join(directory, PRESET_MARKER_FILE))) {
    throw new Error(`dsh-plugin-desktop: preset "${DESKTOP_GIT_BASH_PRESET_ID}" already exists and was not generated by DSH Desktop`)
  }
  rmSync(directory, { recursive: true, force: true })
  mkdirSync(userRoot, { recursive: true })
  cpSync(sourceDirectory, directory, { recursive: true })
  writeFileSync(
    join(directory, 'agent.cordis.yml'),
    gitBashPresetComposition(readFileSync(composition, 'utf8'), bashPath),
  )
  writeFileSync(join(directory, 'preset.yml'), [
    'name: Git Bash',
    'description: Run commands in Git Bash instead of the confined PowerShell. Requires the danger-full-access permission mode: this shell runs outside the Windows file sandbox.',
    '',
  ].join('\n'))
  writeFileSync(join(directory, PRESET_MARKER_FILE), '')
  return { id: DESKTOP_GIT_BASH_PRESET_ID, directory, source }
}
